sagemath/trac-to-github

migrate.cfg.sagetracwikionly, migrate.py
In addition to item A.3. the line-break with respect to headings is corrected (instead of before the line-break is now behind the heading).
=> Fix for item A.3. of issue #18

migrate.py
The patch would also be useful for links to images in attachments in tickets.
=> Fix E1, E13 of issue #18

migrate.py
See https://github.com/kwankyu/trac_to_gh/wiki/GraphTheoryRoadmap
Also fixed the resizing problem of images from attachment. See https://github.com/kwankyu/trac_to_gh/wiki
=> Fix E5 of issue #18

migrate.py
This is the fix I announced in [this comment](https://github.com/sagemath/trac-to-github/pull/26#issuecomment-1350524571) of #26.
The result can be viewd [here](https://github.com/soehms/trac_to_gh/wiki).
=> Fix-E5 and CamelCase at EOL and in display-text of links

migrate.py
Fix https://github.com/sagemath/trac-to-github/issues/18#issuecomment-1358565743
Fix https://github.com/sagemath/trac-to-github/issues/33#issue-1503745087
=> Fix some conversion bugs

migrate.py
=> Remove [[PageOutline]]

migrate.cfg.sagetracmigrationarchive, migrate.py
Fix the broken codeblock in the converted trac-issue 39
See https://github.com/kwankyu/trac_to_gh/wiki/Issue-39
=> Fix codeblock with no newline after {{{

migrate.py
Fix the issue in https://github.com/sagemath/trac-to-github/issues/18#issuecomment-1361894223
And also some other problems in codeblocks, passed unnoticed.
=> Fix bad conversion in codeblock

migrate.py
and fix a bug in codeblocks. 
Response to https://github.com/sagemath/trac-to-github/issues/7#issuecomment-1364775954
=> Add links to comment anchors

migrate.py
See commit links in "New Commits" here
https://github.com/kwankyu/trac_to_gh/wiki/31580
=> Convert commit links to github

migrate.py
and fixed all issues known to me, hopefully.
It is now tricky to deal with all corner cases. I cannot be sure that a fix for one issue may not introduce more issues elsewhere. Fingers crossed. Please check.
back ticks in code snippet still do not work. I don't know how to fix this...
=> Implement GitHub mention

migrate.py
and other failures including
https://github.com/sagemath/trac-to-github/pull/56#issuecomment-1366140000
https://github.com/sagemath/trac-to-github/pull/56#issuecomment-1366325874
=> Fix backticks issue

migrate.py
=> Fix underlined code snippets

migrate.py
Fix the bug reported in https://github.com/sagemath/trac-to-github/pull/60#issuecomment-1366877871
=> Move code to safe place

migrate.cfg.example, migrate.cfg.sagetracmigrationarchive, migrate.cfg.sagetracwikionly, migrate.py
Fix issue #30 
Run wiki conversion once to create the file  wiki_path_conversion_table.txt. Then run again.
=> Fix wiki link problem

migrate.cfg.sagetracmigrationarchive, migrate.py
Fixes #55.
My first PR in 2023. I hoped it to be the last one in 2022.
Happy new year!
=> Fix cgit links

migrate.cfg.example, migrate.cfg.sagetracmigrationarchive, migrate.cfg.sagetracwikionly, migrate.py
Fixed #65 and #66.
And perhaps made the configuration `keep_trac_references` works correctly. If yes, ticket(issue) links are to trac. If no, ticket(issue) links are to github.
=> Fix ticket/issue reference problem

migrate.py
Fix a bug seen in
https://github.com/sagemath/trac_to_gh/blob/main/Issues-09xxx/9808.md#comment:280
=> Fix a bug in quote prefix capturing

migrate.py
See the link to wiki in the (broken) page
https://github.com/sagemath/trac_to_gh/blob/main/Issues-00xxx/456.md
links to wiki should be converted differently in issues
=> Fix wiki links in issues

migrate.py
Fix for https://github.com/sagemath/trac-to-github/pull/89#issuecomment-1369166873
=> Change ../wikis to ../to wiki

migrate.py
=> Fix replying to

migrate.py
Fix for #64 
A file containing the data is created if not exists.
=> Pretty-print the final output

migrate.py
=> Remove spurious usernames

migrate.py
Apart from the last line in the changes for the issue #107, other changes are just refactoring to clean up things.
=> Add comment number to issue comments

migrate.py
=> Fine-tune comment numbers

migrate.py
Reverts sagemath/trac-to-github#122
=> Revert "Fine-tune comment numbers"

migrate.py
=> Remove priority label for invalid tickets

migrate.py
Fix #133.
Check for regression is under way.
=> Fix errors in comment links and attachment links

migrate.py
=> Fix image attachment links

migrate.py
The unmapped users table shows the original user name, is_mention, mannequin username.
Need to remove `unmapped_users.txt` to recreate.
=> Enrich unmapped users table

migrate.py
to gather together similar usernames regardless of the case.
=> Sort with lower-cased username

migrate.cfg.sagetracmigrationarchive
First two from sage-devel.
"anna" is by trac archaeology
=> Add new github names

migrate.cfg.sagetracmigrationarchive, migrate.py
This is just another clean-up concerning project-specific data.
=> Move ignore lists to config files

migrate.cfg.sagetracmigrationarchive
From a message to the final call.
I took this opportunity also to take care of unmapped users up to "factorization".
=> Add bsalisbury1

migrate.py
This fixes some errors seen in #34850.
Most importantly, this fixes a regression introduced in #140.
=> Fix errors in codeblock and comment link

migrate.py
Sort description items in this
`order = ['cc:', 'component', 'keywords', 'author', 'reviewer', 'branch', 'commit', 'depends']`
Other items, if any, follow in alphabetical order.
=> Sort description items by order

migrate.py
Seen many times like in https://34.105.185.241/sagemath/sage-all-2023-01-14-013/issues/16266#issuecomment-4698665
=> Remove comment number from Last 10 new commits

migrate.cfg.sagetracmigrationarchive
As requested in
https://groups.google.com/g/sage-devel/c/-mGnxVr9z1c/m/bKJ4ofd9AQAJ
=> Take care of antoine-leudiere

migrate.py
Seen in https://34.105.185.241/sagemath/sage-all-2023-01-14-015/issues/25270
Compare with https://trac.sagemath.org/ticket/25270 and https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-25xxx/25270.md
=> Fix image attachment in another form

migrate.cfg.sagetracmigrationarchive
Just for sanity.
https://github.com/sagemath/trac-to-github/issues/178#issuecomment-1417068570
=> Fix label colors for milestone duplicate/invalid/wontfix
