migrate.cfg.sagetracwikionly
Add a sample configuration for converting the wiki only. 
This is useful for testing
@dimpase could you please also add your current configuration as a file `migrate.cfg.sagetrac` or something like this?
=> migrate.cfg.sagetracwikionly: New

contributors-from-sage-changelogs.py, contributors-trac-to-github.py
Updated version of the script, now handles comma-separated trac account lists in contributors.xml and outputs a list of Trac accounts without github account - I used this for https://trac.sagemath.org/ticket/34664
contributors-from-sage-changelogs.py: Finds names from https://github.com/sagemath/sage-changelogs/blob/master/merger/contributors/9.7 that are not included in contributors.xml yet -  @kwankyu
=> contributors-trac-to-github.py, contributors-from-sage-changelogs: New

migrate.cfg.sagetracwikionly, migrate.py
According to the [suggestion](https://groups.google.com/g/sage-devel/c/xtwaueSUJI0/m/Ar-GGclIBgAJ) in [this sage-devel-thread](https://groups.google.com/g/sage-devel/c/xtwaueSUJI0/m/0ukw-VrUBwAJ).
=> Add links to Trac tickets for the wiki migration

migrate.py
As mentioned in [this post on sage-devel](https://groups.google.com/g/sage-devel/c/xtwaueSUJI0/m/cEIK9_uSBgAJ), I add the lines of code to translate the alignment instructions. Note that the wiki markup allows these directives to be specified on a cell-by-cell basis. This is used in many examples. AFAIK this can't be properly translated into the GitHub markdown as it only allows to align statements column by column. So I translate the alignments set in the header and ignore all others.
=> Add table alignment instructions

migrate.py
Currently the migration script doesn't convert links that don't have a display text. This will be fixed here.
=> Add missing links

migrate.cfg.sagetracwikionly, migrate.py
To fix the item 4 of issue #18 and the problem described in [this comment](https://github.com/sagemath/trac-to-github/pull/17#issuecomment-1322625241) of PR #17 I implement a class ConversionHelper with a method `wiki_link` to perform the conversion of the special syntax of the Trac wiki page references.
The result of the migration running under this PR can be viewed [here](https://github.com/soehms/trac_to_gh/wiki).
Furthermore, item 7 of #18 is fixed. Note, that the reason for the second example of item 4 is the same as for item 6
=> Fix for items 4 and 7 and completion of item 5 of issue #18

migrate.cfg.sagetracwikionly, migrate.py
As mentioned in the [second comment](https://github.com/sagemath/trac-to-github/issues/18#issuecomment-1321561738) of #18, these two items are due to obscure code in `migration.py`. I'm not removing it entirely, as later it might turn out to be useful in certain situations. So I make it dependent on options that can be set in the configuration file.
This PR depends on PR #19 and PR #21 not because of a functional dependency. It's just to make it easier to interpret the result, which can be viewed [here](https://github.com/soehms/trac_to_gh/wiki)
=> Fix for item A6 and A8 of issue #18

migrate.py, requirements.txt
See https://github.com/kwankyu/trac_to_gh/wiki
Note that trac `WikiStart` page is converted to `WikiStart` instead of `Home`. This makes all pages uniformly converted. Note that `Home` github wiki page is one level up from other pages.
=> Fix E2, E10, E11 of issue #18

migrate.cfg.sagetracmigrationarchive, migrate.py, migration_archive_writer.py
As described in #11, we add a mode for the migration script in which migration archives are written out.
In addition, we write converted tickets (including comments) out as .md files (for inspection of the markup conversion). Results pushed to the temporary wiki, for example https://github.com/sagemath/trac_to_gh/wiki/Issue-39   @kwankyu @soehms
=> Prepare for writing migration archives

migrate.py
implemented issue #48 
also fixed https://github.com/sagemath/trac-to-github/issues/18#issuecomment-1365537676
See https://github.com/kwankyu/trac_to_gh/wiki/27996
and fixed problems in https://github.com/sagemath/trac-to-github/issues/18#issuecomment-1365555570
See https://github.com/kwankyu/trac_to_gh/wiki/34393
=> Some cosmetic changes

migrate.cfg.sagetracmigrationarchive, migrate.cfg.sagetracwikionly, migrate.py
@kwankyu, @mkoeppe I'm sorry I haven't found time to help here for a few weeks. While trying to update myself (at least a bit), I noticed that in the heat of development, a lot of Sage-specific code ended up in the `migration.py` file.
```
(sage-sh) sebastian@ThinkPadKlein:trac-to-github$ grep -ci ^[^\#]*sage migrate.py
102
```
So I'm proposing this PR to relegate this to the config files. The patch produces exactly the same output as the previous commit, but reduces the Sage-specific coding in the Python file:
```
(sage-sh) sebastian@ThinkPadKlein:trac-to-github$ grep -i ^[^\#]*sage migrate.py
Modified and extended for the migration of SageMath from Trac to GitHub.
Decode title prefixes such as [with patch, positive review] used in early Sage tickets.
FORMAT = "%(message)s"
``` …
=> Refactor project specific code

migrate.py
Actually there are not many of them. I collected them into `ignored_usernames`.
They are all `known to Trac: False`, `mention: False` with frequency almost 1.
=> Ignore non-human username unknown to Trac

docs/Migration-Trac-to-Github.md
Add instructions to `docs/Migration-Trac-to-Github.md` on how to work on a migrated open Trac ticket.
This fixes #68.
=> Fix for issue #68

migrate.py
I found more conversion problems:
- wrong url to raw-attachment, seen in https://34.105.185.241/sagemath/sage-all-2023-01-14-014/issues/34850#issuecomment-5614045 (compare with https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-34xxx/34850.md#comment:70)
- missing line after interrupted codeblock, seen in https://34.105.185.241/sagemath/sage-all-2023-01-14-014/issues/1242#issuecomment-5058039 (compare with https://trac.sagemath.org/ticket/1242#comment:2 `}}}` at the end). The missing lines I found are all trivial (or better like in the previous case), but can be significant in principle.
- discontinued quote block, seen in https://34.105.185.241/sagemath/sage-all-2023-01-14-014/issues/34850#issuecomment-5614011 (of course, there are lots of this) (compare with …
=> Fix raw attachment url

migrate.py
There is another form of ticket-comment links, seen in 
https://34.105.185.241/sagemath/sage-all-2023-01-14-015/issues/9512#issuecomment-5696801
(compare with https://trac.sagemath.org/ticket/9512#comment:5 and https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-09xxx/9512.md#comment:5). There are lots of these broken links.
=> Fix ticket-comment links in another form

migrate.py
Seen in https://34.105.185.241/sagemath/sage-all-2023-01-14-015/issues/8156#issuecomment-5677548 (compare with https://trac.sagemath.org/ticket/8156#comment:15).
I removed the phrase "that was inherited from the migration" from  "This is the Trac macro ** that was inherited from the migration", which seems unnecessary and just makes the sentence long.
=> Fix line breaks

migrate.py
I forgot to fix this in the last PR, seen in 
https://34.105.185.241/sagemath/sage-all-2023-01-14-016/issues/15995#comment:0
Note that the parentheses enclosing the arguments are  unbalanced. Compare with 
https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-15xxx/15995.md#comment:0
I did this only for wiki pages in the last PR!
=> Make trac macro sentence short

migrate.py
There are lots of them, corrupting code snippets. 
https://34.105.185.241/sagemath/sage-all-2023-01-14-015/issues/25913#comment:8 vs
https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-25xxx/25913.md#comment:8 vs
https://trac.sagemath.org/ticket/25913#comment:8 vs  
https://34.105.185.241/sagemath/sage-all-2023-01-14-015/issues/26172#comment:11 vs
https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-26xxx/26172.md#comment:11 vs
https://trac.sagemath.org/ticket/26172#comment:11
=> Remove spurious trac macros

migrate.py
Seen in https://34.105.185.241/sagemath/sage-all-2023-01-14-016/issues/24215#comment:18
and in https://34.105.185.241/sagemath/sage-all-2023-01-14-016/issues/10508#comment:84
About `<br>` replacing `<br/>`, it works well. See https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-15xxx/15985.md#comment:9
=> Fix comment link in another form

migrate.py
=> Fix a bug in migrate yes

docs/Migration-Trac-to-Github.md
Perhaps outdated materials after the section "Release Manager's Workflow" needs to be updated or rather deleted. This is not done in this PR.
=> Edit the transition guide from trac to github

migrate.cfg.example, migrate.cfg.sagetracwikionly, migrate.py
Fixes https://github.com/sagemath/trac-to-github/issues/73#issuecomment-1418834768
Perhaps it's not too late. With this PR merged, we convert trac wiki pages again with right ticket links, and then **merge** with existing github wiki pages. There may be some conflicts because people already edited some part of the github wiki pages. But it would be much easier to fix these merge conflicts than manually editing all ticket links in github wiki pages manually!
=> Fix ticket links in wiki conversion
